// English (fallback locale) -- strings for extruder_smoother_fit.html.
window.KV_LOCALES = window.KV_LOCALES || {};
window.KV_LOCALES.en = window.KV_LOCALES.en || {};
window.KV_LOCALES.en.extruder_smoother_fit = {
  title: "Extruder smoother kernel fit — Klipper / Kalico",
  heading: "Extruder smoother kernel fit",
  intro: "With input shaping active, the toolhead&rsquo;s real velocity differs from the commanded one. To keep pressure advance synchronized, the extruder convolves the motion with a polynomial kernel <code>w(t)</code> fitted to approximate the shaped toolhead velocity. Every PA model (linear, <code>tanh</code>, <code>recipr</code>) consumes that smoothed velocity, so kernel quality matters for all of them. This compares the fitted kernel <strong>before</strong> and <strong>after</strong> the <code>extruder_smoother.py</code> rework &mdash; analytic velocity targets, constrained (KKT) least squares, a well-conditioned Legendre basis, and soft non-negativity.",
  groupLabel: "input shaper / smoother",
  legendHint: "Click a legend entry to hide or show that line.",
  caption: 'fitted kernel vs its target velocity profile <span style="color:var(--text-muted)">(normalized time; the kernel should track the target)</span>',
  footer: 'Kernels generated by running the actual host code from <code>upstream/bleeding-edge-v2</code> (old) and the reworked <code>extruder_smoother.py</code> (new) at damping ratio 0.1, then evaluating the fitted polynomial <code>w(t)</code> against the band-averaged analytic target velocity. Fit error is the relative RMS of kernel minus target; magnitudes here use band-averaging and are indicative &mdash; see <a href="https://github.com/KalicoCrew/kalico/pull/909">KalicoCrew/kalico#909</a> for the project&rsquo;s validation figures (e.g. a 100&rarr;20 mm/s corner produces an 8.4 mm/s over-extrusion spike with the old 3hump_ei kernel vs 2.3 mm/s with the new). Rendered with Chart.js.',
  chart: {
    tooltipTau: "tau = {{tau}}",
    tooltipLabel: "{{label}}: {{value}}",
    axisX: "normalized time  tau = t / t_sm",
    axisY: "kernel weight  w(t)*t_sm",
    datasetTarget: "target (ideal)",
    datasetOld: "old kernel",
    datasetNew: "new kernel"
  },
  shapers: {
    zv: "zv",
    mzv: "mzv",
    zvd: "zvd",
    ei: "ei",
    "2hump_ei": "2hump_ei",
    "3hump_ei": "3hump_ei",
    smooth_zv: "smooth_zv",
    smooth_mzv: "smooth_mzv",
    smooth_ei: "smooth_ei",
    smooth_2hump_ei: "smooth_2hump_ei",
    smooth_zvd_ei: "smooth_zvd_ei",
    smooth_si: "smooth_si"
  },
  cards: {
    fitErrorOld: "fit error — old",
    fitErrorNew: "fit error — new",
    improvement: "improvement",
    improvementValue: "{{factor}}× lower",
    improvementNone: "—"
  },
  notes: {
    threeHumpEi: "<strong>3hump_ei sees the largest correction.</strong> The old kernel swings away from its target near the center (it rises while the target dips), desynchronizing pressure advance through step-like velocity changes. On a 100&rarr;20&nbsp;mm/s corner with the printer resonance inside 3hump_ei&rsquo;s design band, that produces an <strong>8.4&nbsp;mm/s over-extrusion transient with the old kernel vs 2.3&nbsp;mm/s with the new</strong> (per PR&nbsp;#909). The new kernel tracks the target across the window.",
    smoothPrefixed: "<code>{{name}}</code> already fitted well; the rework mainly removes finite-difference and conditioning error, roughly halving an already-small fit error. Behaviorally unchanged on real moves (no regression).",
    default: "<code>{{name}}</code>: the new fit tracks the target velocity more closely, lowering the relative RMS fit error. Gains are largest where the target has sharp features the old finite-difference fit smeared or overshot."
  }
};
