// English (fallback locale) -- strings for resonance_excitation.html.
window.KV_LOCALES = window.KV_LOCALES || {};
window.KV_LOCALES.en = window.KV_LOCALES.en || {};
window.KV_LOCALES.en.resonance_excitation = {
  title: "Resonance test excitation explorer — Klipper / Kalico",
  heading: "Resonance test excitation explorer",
  intro: "The motion <code>TEST_RESONANCES</code> commands: frequency ramps at <code>hz_per_sec</code>, each cycle accelerates at <code>accel_per_hz·freq</code>, with an optional slow <code>sweeping</code> oscillation layered on top. The enforced accel/velocity limits are derived from the <em>actual</em> generated sequence; upstream used a fixed formula that ignores the sweeping term.",
  groupLabel: "test generator (from resonance_tester.py)",
  controls: {
    maxFreq: "max_freq (Hz)",
    accelPerHz: "accel_per_hz",
    hzPerSec: "hz_per_sec",
    sweepingPeriod: "sweeping_period (s)",
    sweepingAccel: "sweeping_accel",
    zoomFrequency: "zoom frequency (Hz)"
  },
  legendHint: "Click a legend entry on a chart to hide or show that line.",
  captions: {
    freqVsTime: "frequency vs time <span style=\"color:var(--text-muted)\">(the sweep — rises at hz_per_sec)</span>",
    accelEnvelope: "acceleration envelope vs time <span style=\"color:var(--text-muted)\">(with enforced accel limits)</span>",
    zoomedWaveform: "zoomed waveform at the selected frequency <span style=\"color:var(--text-muted)\">(the actual ± pulse and resulting velocity)</span>"
  },
  footer: "Motion generated by porting <code>VibrationPulseTestGenerator.gen_test</code> and <code>SweepingVibrationsTestGenerator.gen_test</code>. The sequence-derived limits <code>max|accel|+10</code> / <code>max|v|+1</code> come from accumulating the real sequence (as in <code>ResonanceTestExecutor.run_test</code>); upstream used <code>freq_end·accel_per_hz+10</code> and <code>accel_per_hz·0.25+1</code>. <code>sweeping_period=0</code> disables the sweep (its config default); it's set to 0.4 here so the difference is visible. Rendered with Chart.js.",
  note: {
    warn: "<strong>Upstream under-shoots the accel limit.</strong> With sweeping enabled, the true peak acceleration is <code>{{maxA}}</code> mm/s², but upstream’s formula <code>freq_end·accel_per_hz+10 = {{upA}}</code> ignores <code>sweeping_accel</code> — so the machine’s limits wouldn’t be raised enough during the test. The sequence-derived limit is <code>{{brA}}</code>.",
    normal: "Each frequency runs a <code>+accel</code> / <code>−accel</code> pulse lasting <code>0.25/freq</code> each; peak velocity per pulse is <code>accel_per_hz·0.25</code>, independent of frequency. Enable sweeping (period &amp; accel &gt; 0) to see upstream’s fixed limit formula fall short."
  },
  cards: {
    testDuration: "test duration",
    truePeakAccel: "true peak accel",
    accelLimitCompare: "accel limit: sequence vs upstream",
    velLimitCompare: "vel limit: sequence vs upstream"
  },
  values: {
    seconds: "{{value}} s",
    mmPerS2: "{{value}} mm/s²"
  },
  chart: {
    axisFreq: "frequency (Hz)",
    axisTimeS: "time (s)",
    axisAccel: "acceleration (mm/s²)",
    axisTimeMs: "time (ms)",
    axisVelocity: "velocity (mm/s)",
    datasetFrequency: "frequency",
    datasetPeakAccelPos: "+peak accel",
    datasetPeakAccelNeg: "-peak accel",
    datasetLimitSequence: "limit (from sequence)",
    datasetLimitUpstream: "limit (upstream formula)",
    datasetAccel: "accel",
    datasetVelocity: "velocity",
    tooltipLabel: "{{label}}: {{value}}"
  }
};
